"""initial

Revision ID: 5e26389b73e0
Revises: 
Create Date: 2026-07-08 16:04:48.319265
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e26389b73e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_wagered', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_won', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', name='uq_users_telegram_id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('bets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bet_id_external', sa.String(length=100), nullable=True),
    sa.Column('bet_type', sa.Enum('SINGLE', 'ACCUMULATOR', 'SYSTEM', 'LIVE', name='bettype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'WON', 'LOST', 'CANCELLED', 'VOID', name='betstatus'), nullable=False),
    sa.Column('stake', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('potential_return', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('actual_return', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('odds', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('sport', sa.String(length=100), nullable=False),
    sa.Column('league', sa.String(length=200), nullable=True),
    sa.Column('event_name', sa.String(length=500), nullable=False),
    sa.Column('event_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('selection', sa.Text(), nullable=False),
    sa.Column('selection_odds', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'bet_id_external', name='uq_bets_user_external')
    )
    op.create_index(op.f('ix_bets_bet_id_external'), 'bets', ['bet_id_external'], unique=False)
    op.create_index(op.f('ix_bets_user_id'), 'bets', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id_external', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'BET_PLACED', 'BET_WON', 'BET_LOST', 'BET_REFUND', 'BONUS', 'FEE', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_bet_id'), 'transactions', ['bet_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id_external'), 'transactions', ['transaction_id_external'], unique=True)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_id_external'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_bet_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_bets_user_id'), table_name='bets')
    op.drop_index(op.f('ix_bets_bet_id_external'), table_name='bets')
    op.drop_table('bets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
